[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[functions]
  included_files = ["data/presets/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://vierradev.com"
